title: Greg Augustine
logo: /headshot.jpg
description: Welcome to my homepage.  Get in touch with me via <a href="mailto:gregory.augustine@ndsu.edu">email</a> or on <a href="https://www.linkedin.com/in/graugustine/">LinkedIn</a>.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
