title: Greg Augustine
logo: /headshot.jpg
description: Welcome to my homepage.  Get in touch with me via [email](mailto:gregory.augustine@ndsu.edu).
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
